name: veracode-scan
on:
  push:
    branches: [feature-1]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install gems
        run : |
          bundle install --without development test
      
      - name: packaging to veracode scan
        run : |
           bundle update veracode
           veracode prepare -v

      - name: publishing artifact
        uses: actions/upload-artifact@v2
        with:
          name: veracode-package
          path: tmp/

  veracode-sca:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: sca agent-based scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS

  veracode_static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: veracode-package
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'railsgoat-demo'
          createprofile: false
          filepath: 'tmp/'
          vid: '${{ secrets.VID }}'
          vkey: '${{ secrets.VKEY }}'

  veracode-sast-pipeline-scan:
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: veracode-package
          
      - name: scan 
        run: |
          ls -l
          java -jar /opt/veracode/pipeline-scan.jar -vid "${{ secrets.VID }}" -vkey "${{ secrets.VKEY }}" -f "tmp/*.zip" -p "RailsGoat-Demo"
