name: veracode-scan
on:
  push:
    branches: [feature-1]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install rvm
        run: |
          gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash -s stable
          curl -sSL https://get.rvm.io | bash -s stable --rails

      - name: install gems
        run : |
          bundle -v
 